// Code generated by protoc-gen-gotemplate. DO NOT EDIT.
package v1

import (
	context "context"
	fmt "fmt"

	daprc "github.com/dapr/go-sdk/client"
	common "github.com/dapr/go-sdk/service/common"
	content "github.com/kzmake/dapr-kit/content"
	proto "github.com/kzmake/dapr-kit/content/proto"
	invoke "github.com/kzmake/dapr-kit/invoke"
	grpc "google.golang.org/grpc"
)

const _ = daprc.UndefinedType
const _ = common.SubscriptionResponseStatusSuccess
const _ = invoke.DaprPackageIsVersion1
const _ = grpc.SupportPackageIsVersion7

var _ fmt.Stringer
var _ context.Context

const AliceServiceName = "api.alice.v1.AliceService"

// AliceServiceHandler ...
type AliceServiceHandler interface {
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
}

// RegisterAliceServiceInvocationHandlers ...
func RegisterAliceServiceInvocationHandlers(s common.Service, impl AliceServiceHandler) error {
	fns := map[string]invoke.HandlerFunc{
		"api.alice.v1.AliceService/Handle": _AliceService_Handle_Invocation_Handler(impl.Handle),
	}

	for name, fn := range fns {
		if err := s.AddServiceInvocationHandler(name, fn); err != nil {
			return err
		}
	}

	return nil
}

func _AliceService_Handle_Invocation_Handler(handler interface{}) invoke.HandlerFunc {
	return func(ctx context.Context, in *common.InvocationEvent) (*common.Content, error) {
		b, err := content.NewBinder(in.ContentType)
		if err != nil {
			return nil, err
		}

		req := new(HandleRequest)
		if err := b.Unmarshal(in.Data, req); err != nil {
			return nil, err
		}

		fn := handler.(func(context.Context, *HandleRequest) (*HandleResponse, error))
		res, err := fn(ctx, req)
		if err != nil {
			return nil, err
		}

		d, err := b.Marshal(res)
		if err != nil {
			return nil, err
		}

		out := &common.Content{
			DataTypeURL: "api.alice.v1.AliceService/Handle",
			ContentType: "application/json",
			Data:        d,
		}

		return out, nil
	}
}

type AliceServiceInvocationClient interface {
	Handle(context.Context, *HandleRequest, ...grpc.CallOption,) (*HandleResponse, error)
}

type AliceserviceInvocationClient struct {
	appID string
	conn  *grpc.ClientConn
}

func NewAliceServiceInvocationClient(appID string, conn *grpc.ClientConn) AliceServiceInvocationClient {
	return &AliceserviceInvocationClient{
		appID: appID,
		conn:  conn,
	}
}

func (c *AliceserviceInvocationClient) Handle(
	ctx context.Context, in *HandleRequest, opts ...grpc.CallOption,
) (*HandleResponse, error) {
	cc := daprc.NewClientWithConnection(c.conn)

	b := proto.NewBinder()

	req, err := b.Marshal(in)
	if err != nil {
		return nil, err
	}

	res, err := cc.InvokeMethodWithContent(ctx, c.appID, "api.alice.v1.AliceService/Handle", "POST", &daprc.DataContent{
		ContentType: "application/x-protobuf",
		Data:        req,
	})
	if err != nil {
		return nil, err
	}

	out := new(HandleResponse)
	if err := b.Unmarshal(res, out); err != nil {
		return nil, err
	}

	return out, nil
}
