// Code generated by protoc-gen-gotemplate. DO NOT EDIT.
package v1

import (
	context "context"
	fmt "fmt"

	daprc "github.com/dapr/go-sdk/client"
	common "github.com/dapr/go-sdk/service/common"
	binding "github.com/kzmake/dapr-kit/binding"
	encoding "github.com/kzmake/dapr-kit/encoding"
	proto "github.com/kzmake/dapr-kit/encoding/proto"
	invoke "github.com/kzmake/dapr-kit/invoke"
	grpc "google.golang.org/grpc"
)

const _ = daprc.UndefinedType
const _ = common.SubscriptionResponseStatusSuccess
const _ = grpc.SupportPackageIsVersion7

var _ fmt.Stringer
var _ context.Context
var _ invoke.Def
var _ binding.Def

const AliceServiceName = "api.alice.v1.AliceService"

// AliceServiceHandler ...
type AliceServiceHandler interface {
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
}

// RegisterAliceServiceInvocationHandler ...
func RegisterAliceServiceInvocationHandler(s common.Service, impl AliceServiceHandler) error {
	fns := map[string]invoke.Func{
		"api.alice.v1.AliceService/Handle": _AliceService_Handle_Invocation_Handler(impl.Handle),
	}

	for name, fn := range fns {
		if err := s.AddServiceInvocationHandler(name, fn); err != nil {
			return err
		}
	}

	return nil
}

func _AliceService_Handle_Invocation_Handler(handler interface{}) invoke.Func {
	return func(ctx context.Context, in *common.InvocationEvent) (*common.Content, error) {
		e, err := encoding.New(in.ContentType)
		if err != nil {
			return nil, err
		}

		req := new(HandleRequest)
		if err := e.Unmarshal(in.Data, req); err != nil {
			return nil, err
		}

		fn := handler.(func(context.Context, *HandleRequest) (*HandleResponse, error))
		res, err := fn(ctx, req)
		if err != nil {
			return nil, err
		}

		d, err := e.Marshal(res)
		if err != nil {
			return nil, err
		}

		out := &common.Content{
			DataTypeURL: "api.alice.v1.AliceService/Handle",
			ContentType: "application/json",
			Data:        d,
		}

		return out, nil
	}
}

// RegisterAliceServiceBindingHandler ...
func RegisterAliceServiceBindingHandler(s common.Service, impl AliceServiceHandler) error {
	fns := map[string]binding.Func{
		"api.alice.v1.AliceService/Handle": _AliceService_Handle_Binding_Handler(impl.Handle),
	}

	for name, fn := range fns {
		if err := s.AddBindingInvocationHandler(name, fn); err != nil {
			return err
		}
	}

	return nil
}

func _AliceService_Handle_Binding_Handler(handler interface{}) binding.Func {
	return func(ctx context.Context, in *common.BindingEvent) ([]byte, error) {
		e := proto.NewEncoding()

		req := new(HandleRequest)
		if err := e.Unmarshal(in.Data, req); err != nil {
			return nil, err
		}

		fn := handler.(func(context.Context, *HandleRequest) (*HandleResponse, error))
		res, err := fn(ctx, req)
		if err != nil {
			return nil, err
		}

		d, err := e.Marshal(res)
		if err != nil {
			return nil, err
		}

		return d, nil
	}
}

type AliceServiceInvocationClient interface {
	Handle(context.Context, *HandleRequest, ...grpc.CallOption) (*HandleResponse, error)
}

type aliceserviceInvocationClient struct {
	appID string
	conn  *grpc.ClientConn
}

func NewAliceServiceInvocationClient(appID string, conn *grpc.ClientConn) AliceServiceInvocationClient {
	return &aliceserviceInvocationClient{
		appID: appID,
		conn:  conn,
	}
}

func (c *aliceserviceInvocationClient) Handle(
	ctx context.Context, in *HandleRequest, opts ...grpc.CallOption,
) (*HandleResponse, error) {
	cc := daprc.NewClientWithConnection(c.conn)

	e := proto.NewEncoding()

	req, err := e.Marshal(in)
	if err != nil {
		return nil, err
	}

	res, err := cc.InvokeMethodWithContent(ctx, c.appID, "api.alice.v1.AliceService/Handle", "POST", &daprc.DataContent{
		ContentType: "application/x-protobuf",
		Data:        req,
	})
	if err != nil {
		return nil, err
	}

	out := new(HandleResponse)
	if err := e.Unmarshal(res, out); err != nil {
		return nil, err
	}

	return out, nil
}

type AliceServiceBindingClient interface {
	Handle(context.Context, *HandleRequest, map[string]string) (*HandleResponse, error)
}

type aliceserviceBindingClient struct {
	conn *grpc.ClientConn
}

func NewAliceServiceBindingClient(conn *grpc.ClientConn) AliceServiceBindingClient {
	return &aliceserviceBindingClient{
		conn: conn,
	}
}

func (c *aliceserviceBindingClient) Handle(
	ctx context.Context, in *HandleRequest, meta map[string]string,
) (*HandleResponse, error) {
	cc := daprc.NewClientWithConnection(c.conn)

	e := proto.NewEncoding()

	d, err := e.Marshal(in)
	if err != nil {
		return nil, err
	}

	req := &daprc.InvokeBindingRequest{
		Name:      "api.alice.v1.AliceService/Handle",
		Operation: "create",
		Data:      d,
		Metadata:  map[string]string{},
	}

	res, err := cc.InvokeBinding(ctx, req)
	if err != nil {
		return nil, err
	}
	if err != nil {
		return nil, err
	}

	out := new(HandleResponse)
	if err := e.Unmarshal(res.Data, out); err != nil {
		return nil, err
	}

	return out, nil
}

type AliceServiceOutputBindingClient interface {
	Handle(context.Context, *HandleRequest, map[string]string) error
}

type aliceserviceOutputBindingClient struct {
	conn *grpc.ClientConn
}

func NewAliceServiceOutputBindingClient(conn *grpc.ClientConn) AliceServiceOutputBindingClient {
	return &aliceserviceOutputBindingClient{
		conn: conn,
	}
}

func (c *aliceserviceOutputBindingClient) Handle(
	ctx context.Context, in *HandleRequest, meta map[string]string,
) error {
	cc := daprc.NewClientWithConnection(c.conn)

	e := proto.NewEncoding()

	d, err := e.Marshal(in)
	if err != nil {
		return err
	}

	req := &daprc.InvokeBindingRequest{
		Name:      "api.alice.v1.AliceService/Handle",
		Operation: "create",
		Data:      d,
		Metadata:  map[string]string{},
	}

	if err := cc.InvokeOutputBinding(ctx, req); err != nil {
		return err
	}

	return nil
}
