// Code generated by protoc-gen-gotemplate. DO NOT EDIT.
package v1

import (
	context "context"

	common "github.com/dapr/go-sdk/service/common"
	invoke "github.com/kzmake/dapr-kit/invoke"
)

const GreeterServiceName = "api.greeter.v1.GreeterService"

// aliases
type (
	invocationHandler = func(context.Context, *common.InvocationEvent) (*common.Content, error)
)

// GreeterServiceHandler ...
type GreeterServiceHandler interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// RegisterGreeterServiceInvocationHandlers ...
func RegisterGreeterServiceInvocationHandlers(s common.Service, impl GreeterServiceHandler) error {
	return invoke.RegisterInvocationHandlers(s, impl, GreeterServiceName)
}
