// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: example/binding-priority-queue/event/bob/v1/bob.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata map[string]string `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescGZIP(), []int{0}
}

func (x *HandleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HandleRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HandleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescGZIP(), []int{1}
}

var File_example_binding_priority_queue_event_bob_v1_bob_proto protoreflect.FileDescriptor

var file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDesc = []byte{
	0x0a, 0x35, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x2d, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2d, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x62, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6f,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x62,
	0x6f, 0x62, 0x2e, 0x76, 0x31, 0x22, 0xa3, 0x01, 0x0a, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x64, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x62, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b,
	0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x10, 0x0a, 0x0e, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x51, 0x0a,
	0x0a, 0x42, 0x6f, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x62, 0x6f,
	0x62, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x62, 0x6f, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x7a, 0x6d, 0x61, 0x6b, 0x65, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2d, 0x6b, 0x69, 0x74, 0x2f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2d, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2f, 0x62, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescOnce sync.Once
	file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescData = file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDesc
)

func file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescGZIP() []byte {
	file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescOnce.Do(func() {
		file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescData)
	})
	return file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDescData
}

var file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_binding_priority_queue_event_bob_v1_bob_proto_goTypes = []interface{}{
	(*HandleRequest)(nil),  // 0: event.bob.v1.HandleRequest
	(*HandleResponse)(nil), // 1: event.bob.v1.HandleResponse
	nil,                    // 2: event.bob.v1.HandleRequest.MetadataEntry
}
var file_example_binding_priority_queue_event_bob_v1_bob_proto_depIdxs = []int32{
	2, // 0: event.bob.v1.HandleRequest.metadata:type_name -> event.bob.v1.HandleRequest.MetadataEntry
	0, // 1: event.bob.v1.BobService.Handle:input_type -> event.bob.v1.HandleRequest
	1, // 2: event.bob.v1.BobService.Handle:output_type -> event.bob.v1.HandleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_binding_priority_queue_event_bob_v1_bob_proto_init() }
func file_example_binding_priority_queue_event_bob_v1_bob_proto_init() {
	if File_example_binding_priority_queue_event_bob_v1_bob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_binding_priority_queue_event_bob_v1_bob_proto_goTypes,
		DependencyIndexes: file_example_binding_priority_queue_event_bob_v1_bob_proto_depIdxs,
		MessageInfos:      file_example_binding_priority_queue_event_bob_v1_bob_proto_msgTypes,
	}.Build()
	File_example_binding_priority_queue_event_bob_v1_bob_proto = out.File
	file_example_binding_priority_queue_event_bob_v1_bob_proto_rawDesc = nil
	file_example_binding_priority_queue_event_bob_v1_bob_proto_goTypes = nil
	file_example_binding_priority_queue_event_bob_v1_bob_proto_depIdxs = nil
}
