// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BobServiceClient is the client API for BobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BobServiceClient interface {
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
}

type bobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBobServiceClient(cc grpc.ClientConnInterface) BobServiceClient {
	return &bobServiceClient{cc}
}

func (c *bobServiceClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, "/event.bob.v1.BobService/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BobServiceServer is the server API for BobService service.
// All implementations must embed UnimplementedBobServiceServer
// for forward compatibility
type BobServiceServer interface {
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
	mustEmbedUnimplementedBobServiceServer()
}

// UnimplementedBobServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBobServiceServer struct {
}

func (UnimplementedBobServiceServer) Handle(context.Context, *HandleRequest) (*HandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedBobServiceServer) mustEmbedUnimplementedBobServiceServer() {}

// UnsafeBobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BobServiceServer will
// result in compilation errors.
type UnsafeBobServiceServer interface {
	mustEmbedUnimplementedBobServiceServer()
}

func RegisterBobServiceServer(s grpc.ServiceRegistrar, srv BobServiceServer) {
	s.RegisterService(&_BobService_serviceDesc, srv)
}

func _BobService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BobServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.bob.v1.BobService/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BobServiceServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.bob.v1.BobService",
	HandlerType: (*BobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _BobService_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/binding-priority-queue/event/bob/v1/bob.proto",
}
